export { default as Header } from '@/components/layout/Header'
export { default as Footer } from '@/components/layout/Footer'
export { default as CartDrawer } from '@/components/cart/CartDrawer'
export { default as BottomNav } from '@/components/layout/BottomNav'
export { DeferredChatWidget } from '@/components/chat/DeferredChatWidget'
export { default as CookieConsentBanner } from '@/components/consent/CookieConsentBanner'
export { default as CompareBarWrapper } from '@/components/products/CompareBar'
export { ThemeProvider } from '@/components/theme/ThemeProvider'
export { default as WebVitalsReporter } from '@/components/WebVitalsReporter'
